exports.seed = function (knex) {
      return knex('articleBlock').del()
  .then(async ()=>{
      return knex('articleBlock').insert([{
          article_id: 1,
          type: 'text',
          text: "As we enter a hyper-consumerist era governed by “big data” and “surveillance capitalism”, data has become an all-powerful technocratic instrument in the negotiation of many socio-political sectors, including the negotiations within Climate Politics. According to the market intelligence agency IDC, global data reached up to an astonishing data cap of 18 zettabytes in 2018 with no signs of slowing down whatsoever. In the UK alone, there are over 1500 sites, which monitor air quality - these monitoring networks, in turn, continuously gather and process data in real-time. Although these networks continuously produce a wide range of both descriptive and exceedance statistics, not all data produced is easily accessible for the public realm, and neither does it remain unchallenged by other information sources. Both governments and high-technology corporations now compete to gather and analyze data, at the expense of their respective citizens’ and consumers’ health and privacy. It has become an ultimate quest to gather, process, and to manipulate as much data as one can for financial profit - to meet certain environmental quotas, such as UK Air Quality Objectives, EU Limit and Target Values, and Critical Loads . Data abstraction and spreading misinformation have become powerful tools for such agencies, and to objectively interpret available datasets has become an increasingly challenging task for the general populace."
      }, {
          article_id: 1,
          type: 'text',
          text: "Many new readers may be unfamiliar with this open hostility, as it has been cleverly masked by numerous agencies involved in this conflict. A clear example of this is the UK’s commitment to reduce greenhouse gas emissions to net zero by 2050 to meet the suggested quotas by the National Air Quality Standards. These discussions, however, cleverly avoids the discussions of the ever-increasing offshoring of CO2 emissions. This includes discussions of importing carbon-intensive goods and electricity from overseas - during the “coal free” fortnight in 2019, no domestic coal was used to power the UK grid, however, the UK imported an estimated 40.5 GWH of Dutch coal-generated electricity. The data and the information involved in this event was cleverly avoided by the apparatus of ubiquity and the promises of a “greener tomorrow”. Energy and Infrastructure analyst Tony Lodge further describes  this in his lecture “The Great Carbon Swindle” in regards to how the UK is able to cleverly mask the emissions involved in supply chains and how it avoids carbon levies through layers of convoluted bureaucracy. This has become much more imminent in recent years, as the UK now imports six times more electricity than it exports, which is currently exempt from carbon levies. This, fundamentally, confuses the general populace, who cannot know the actual source of electricity that they are using. In short, this has become an open hostility to acquire the “real picture” of UK sustainability."
      }, {
          article_id: 1,
          type: 'text',
          text: 'The same principle applies to the UK’s construction and agricultural sectors. Greenhouse gas emissions from imported goods and raw materials, e.g. steel, coal, brick, etc. are currently exempt in UK statistics, thus allowing the UK to continue using carbon-intensive energy and goods, while appearing to meet both domestic and EU emission targets. A clear example of this is the UK promise of shutting down domestic coal pits - in truth, millions of tonnes of coal were imported overseas over the last few years for industrial use, thereby hiding the real picture of UK greenhouse gas emissions. Additional emissions costs incurred by transportation of these goods were also exempt in these statistics, thus providing a dishonest image of UK gas emissions. This data warfare has ultimately led to an intense discrimination against domestic UK companies (which are subject to climate levies), compared to their overseas competitors. The manipulation and abstraction of data have become powerful tools to direct domestic climate change policies, which may, in fact, be detrimental to the UK in the long run.'
      },{
          article_id: 1,
          type: 'text',
          text: 'Although “free goods”, such as the air that we breathe, has remained as a non-commodity, the data surrounding it has either become private or commercialized. Although most Londoners will agree that monitoring air pollutants is key to monitoring climate change in cities, very few are able to answer the question “Where does this data go?” Some say the government, and others say Google, or some other high-technology corporation. Quick Google-searches lead to websites, such as the London Air Quality Network, which provides abstractified air pollutant maps, either in “real-time” or on an annual basis. However, on closer inspection, a new question arises: “Why is the data abstractified?” Abstract data maps imply that detailed data is unavailable for the public realm, and can only be requested either via filling out forms or via purchase. Here, we see that “free goods” have become questionable for consumption; it renders requirements for basic human needs as commodities, while leaving “free goods” untouched as non-commodities.'
      },{
          article_id: 1,
          type: 'text',
          text: 'This has become particularly evident in London, where raw data is very rarely accessible for the general populace. Processed data sets and abstract data maps of carbon dioxide are now widely accessible through the London Datastore and the UK NAEI (National Atmospheric Emissions Inventory) at no to little cost whatsoever, however, this data is limited. Other datasets provided by government networks are subject to OGL (Open Government License), and under the constraints of OGL, numerous agencies are able to combine their data with government-licensed datasets to exploit this data both commercially and non-commercially. They are able to adapt, manipulate, and publish this data in conjunction with their own product and/or application; thus,  it becomes somewhat easy to spread misinformation under the guise of “government-licensed datasets.” In addition, real-time measurements of CO2 levels in the UK are almost always processed and abstractified, provided in either monthly or yearly intervals. '
      },{
          article_id: 1,
          type: 'bannerImageStart',
          attachmentLink: 'https://aarchitecture.blob.core.windows.net/videos/ezgif.com-gif-maker.gif',
          attachmentCaption: 'Demo of AR application visualising movement of CO2 (2021) © Yeha Kim'
      },{
          article_id: 1,
          type: 'text',
          text: 'Unexplained splotches and missing data are somewhat common in such abstracted datasets, such as the modeled background pollution data maps. This includes background pollution maps at 1 x 1 km resolution, which are modeled under Defra’s MAAQ (Modeling of Ambient Air Quality) contract to fulfill UK’s CO2 reporting obligations to the EU. Although this data is publicly available for research applications (e.g. university studies and public health surveys), there are key grid squares, which are currently labeled as “missing”. To complement this missing data, UK’s Defra suggests to utilize alternative Local Authority-specific maps, which are based on the same CO2 monitoring and modeling tools. This convoluted bureaucracy of recording and managing data maps has gradually become a key hurdle in understanding the “real picture” of UK sustainability. However, the general populace can do very little, but to accept the provided abstracted data. The question of missing data, in turn, raises additional questions - why is the data missing to begin with?'
      },{
          article_id: 1,
          type: 'text',
          text: 'Here, one can observe that the dispossession of the information surrounding “free goods”, however, this process of dispossession is no longer a mere abstraction. It is conducted through well-thought out operational practices, where either limited raw data or abstracted datasets are presented as full datasets to the general populace. This seemingly transparent attitude taken by various government and environmental agencies cannot be anything further than the truth. The datafication of “free goods” ultimately leads to stores of privatized raw data and unaltered knowledge, only accessible by a few. It illustrates that the apparatus of ubiquity is, in fact, a method to overcome the hurdles involved in the general populace’s fundamental human rights to non-commodities. This is further accomplished by the movement of data, as illustrated by NAEI’s FAQ section, under the question “Are there UK emission maps for previous years?”. According to the NAEI, “UK emission maps are only available for the latest inventory year [...] [and they] do not generate a time series of emissions maps for trend analysis.” Where then does the data for previous years go? Recalcitrant citizens will only number in a few; agencies will always argue that the general populace will always have access to both raw (albeit limited) and abstracted data, which they argue, is “more than enough”. No moral or legal constraints will stand in the way for such agencies, as long as they are ubiquitous enough to satisfy the general populace.'
      },{
          article_id: 1,
          type: 'text',
          text: 'It is no surprise that “big data” capitalism has begun to meticulously catalog “free goods”, thereby establishing “non-commodities” as potential commodities in the near future. Although the datafication of environmental “free goods" has shed light on the ongoing issues of climate change, the manipulation and abstraction of datasets has ultimately led to an inward sense of valid truth and moral authority. The general populace is currently divided in terms of responding to the ongoing challenges of climate change. Full and objective datasets have been rendered useless in favor of rejection of genuine reciprocity. It offers a new template for future climate change policies, where the “real picture” is forfeit for others’ profit. It has become much more difficult to discern the truth in the fog of utopian rhetoric conjured by numerous profit-driven agencies. In short, this becomes a question of the ownership of environmental “free goods” data? Who has access to it? Who knows? Who decides who knows? Failure to answer these questions will inevitably lead to more hidden pollution, insecure UK power supplies and, ultimately, more global greenhouse gas emissions.'
      },{
          article_id: 1,
          type: 'text',
          text: 'It becomes self-evident that the “Warm War” is an open hostility between the general populace and numerous governmental and private agencies for the access of data. The modus operandi of this war is through the collection, abstraction and the movement of data. It is a negotiation to satisfy both sides of the conflict without committing to tangible solutions and concrete targets. A new transparent approach must be implemented to level the global playing field and to cut overall emissions worldwide. The raw data of “free goods” must be circulated among the general populace to incentivise renewed discussions, which, in turn, may lead to decisive action.'
      },{
          article_id: 2,
          type: 'titleBlockB'
      },{
          article_id: 2,
          type: 'textRight',
          text: "Dotcom Séance is an on-chain spiritism NFT session to revive ghosts of companies that crashed in the dot-com bubble. It revives web 1 business models as web3 token groups that become ad-hoc DAOs, internet history through time and code. Twenty-one dotcom era companies have been summoned for revival. Each company includes an ENS domain, a new logo-NFT designed by Guile Twardowski—the artist behind Cryptokitties—and a suite of hidden text-to-image logo-NFTs by a CLIP/Diffusion text-to-image ML model that Guile drew inspiration from. Minting any NFT allows you to claim a subdomain on the company's new ENS domain. Owner of the Twardowski logo-NFTs earns the title of CEO on each company's profile page."
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: 'https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Leonora%20Carrington%20and%20Max%20Ernst%20(1937)%20by%20Lee%20Miller.jpg',
          attachmentCaption: 'Leonora Carrington pictured with Max Ernst - Lee Miller, 1937'
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'A question at the forefront of my head when I’m in an art gallery is: what shoes do people wear to galleries? Do they go for comfort? Do they go garmy? Do they veil their pretention with knackered reeboks? Do they try to impress a crowd that might be inclined to gag at an Ugg or side-eye a slipper?\n\nI of course think that art galleries should be filled with bare-footed people. We’re all less judgemental of one another when our feet are out and the floor becomes communal; perhaps our engagement with art can also be enriched this way. Chris Ofili grounds his work by propping it up with balls of elephant dung, which he says connects them to the earth. He may have a point. Alas, the AF1s, Chelsea boots, Dickies, Docs and Crocs squeak on in. I’m not claiming any cultural high ground here, I feel invincible in my tangerine 95s and haven’t yet taken them off them at a gallery. Baby steps.',
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: 'https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Sketch%20by%20Mich%20Rossiter.jpg',
          attachmentCaption: "Sketch of Roland Penrose's The Last Voyage of Captain Cook (1936-67) by Mich Rossiter, 2022"
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'No Ofili today, though. The Tate’s newest headline offering is Surrealism Beyond Borders, an exhibition loan from the New York Met acting as a Marvel-style origin story for Surrealism (the First Avenger?). The exhibition’s timeline, although heavily-*curated*, succeeds in threading a clear narrative through a series of snaking spaces, dividing Surrealism into its focal cities, periods and sub-movements.\n\nOne of Tate’s proudest achievements, so they proclaim immediately after the ticket desk, is that they ARE NOT BEING EUROCENTRIC TODAY, NOPE NOT TODAY, COME BACK ANOTHER DAY FOR THAT MAYBE. I’m paraphrasing. And there are in fact beautiful, pneumatic works by artists who were based in Martinique, Cairo, Tokyo, Puerto Rico and Mexico, as well as Europe. The geographical and cultural breadth of the exhibition invites visitors to join some conceptual dots in their heads, in order to appreciate the movement’s poignant scope and versatility. After the dot-joining, we see that core Surrealist principles and manifestoes are moulded by environmental factors, political landscapes and societal boundaries in each artist’s world, rather than by a projection of European life. This is special and results in a series of spaces that give raw, incisive accounts of the artists’ lives.'
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: 'https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Untitled%20(1939)%20by%20Ramses%20Younan.jpg',
          attachmentCaption: 'Excerpt: Untitled - Ramses Younan, 1939'
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'This landscape of multiplicity is gripping. From it, common threads of radical political action, anti-imperialism and collective conscience are crystalised. Between Ramses Younan’s disassembled, monolithic dune figures, contortedly lounging in a baking hot daze, and Remedios Varo’s personal dystopia, longing for her lover as she “Embroider[s] the Earth’s Mantle” as one of six drone embroiderers, sit more overt fragments of political struggle. The most poignant is ‘Liberté est un mot vietnamien’ by a large group of surrealists led by Yves Bonnefoy and Andre Breton. The 1947 piece is an anti-imperialist manifesto imploring that France ends its post-war occupation of Vietnam. In fact, many of these works are acts of resistance, made in a broiling inter-war world seething with the possibility of violence.'
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: "https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Embroidering%20the%20Earth's%20Mantle%20by%20Remedios%20Varo.jpg",
          attachmentCaption: "Embroidering the Earth's Mantle - Maria Remedios Varo, 1961"
      },{
          article_id: 6,
          type: 'quote',
          text: '*“We cannot defend freedom here while imposing servitude elsewhere. Surrealism, whose great objective as always is the liberation of mankind, can hardly remain silent at such senseless and revolting criminality.”*\n\n– Paris-based surrealists, April 1947'
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'Facets of the work on display here clearly speak to our time. A blindingly *Surrealist* contrast emerges from the images of war in Ukraine that linger in our heads on this rainy Tuesday. Space 1: two freshers, I suspect on a second or third date, are more interested in each other than the work around them and hold hands. Space 2: two thousand kilometres away, a child traces the condensation around her mother’s hand on the other side of the glass of a Kyiv train window – she may never see her again.\n\nAway from the Tate’s self-gratifying (and definitely not Eurocentric!) proclamations, an empty space around a corner of Room 3 attracts me. I explore it and conclude that I’ve found the most radical piece of Surrealism in the exhibition: a heavy, dark corner, quizzically jet black amidst the diffused spotlights, and a complete mystery to the Tate invigilators. A part of me doesn’t think that the Tate would pull this off, though it did feel a charge and gravitas in the space that spoke of intention. I love it.'
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'Part of my obsession with what might be a fire escape is a result of the exhibition’s emphatic disinterest with contemporary Surrealist practice. Surrealism Is Not Dead would be a fantastic counter-exhibition to this, and would emphasise that Surrealism in 2022 is an alive, breathing, talking, shouting thing. Breton’s baton is in hand and artists today are running with it. To respect and do these multiple Surrealist movements justice, contemporary work should be chronologised and engaged with. This could help promote young artists too often excluded from the Tate’s retrospective-heavy calendar.'
      },{
          article_id: 6,
          type: 'quote',
          text: '*“We cannot defend freedom here while imposing servitude elsewhere. Surrealism, whose great objective as always is the liberation of mankind, can hardly remain silent at such senseless and revolting criminality.”*'
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'And so instead of communicating and celebrating Surrealisms as plural, living, breathing movements, Tate presents SurrealismTM: the kooky, sexy assortment of idea-debris that once mattered, but no longer does. So why the silence? Why the decomposing *dead* body of work?\n\nPart of the problem is that the Tate presents these works as actually *sur*-realist, striking a naïve and destructive tone. Surrealists never claimed to be escaping from reality; on the contrary they were challenging and holding to account the present, using accident and the sub-conscious to unveil concealed truths. To present these works as other-worldly is to betray a blindness to the ridiculous reality we already inhabit. This approach reveals collective positions of privilege and may even entrench privilege. To promote and fund work that significantly reflects on and challenges our society and modern dispositions may be too close for comfort for those in power. They would respond with culture warring counter-attacks and complaints that we haven’t had enough Turner or Van Gogh exhibitions before things can get too *poli(s)tic-ky*.'
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: 'https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Coups%20de%20Ba%CC%82tons%20(1937)%20by%20Mayo.jpg',
          attachmentCaption:'Excerpt: ‘Coup de Bâton’, Mayo, 1937'
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'Maybe Dark Corner is the work of a young vigilante Surrealist, working as a member of entry- to mid-level Tate staff who wasn’t culled during the pandemic. Well, vigi-Surrealist, it banged and I’ll be looking out for what you do next.'
      },{
          article_id: 6,
          type: 'quote',
          text: '*“Hey look there’s a train coming out of a mantelpiece – that’s  mad! Skrrt, look at these mangled bodies – wacky! Wow look at this *political struggle*, imagine waking up to that everyday – wild! I love an escape, what a great exhibition. Let’s get a coffee – Flat White, please.”*\n\nThought-track portrait of the Tate-goer most likely to buy a catalogue and maybe a print at the gift shop\n\nMich Rossiter, 2022'
      },{
          article_id: 6,
          type: 'textSparse',
          text: 'And so as the exhibition continues and transitions into an after-life as bedroom postcards, living room table books and IG highlights, I wonder when today’s Surrealists will get their time. I suspect some of Surrealism’s best work remains hidden to us, not yet made or made in parts of the world seeing crisis or quiet, such as the frontlines of eco-climatic breakdown, lands of industrialised violence, or parts of the world simply given little time by our media and arts. Like Leonora Carrington, they likely “don’t have time to be anyone’s muse” and won’t appear in a Tate Near You anytime soon. Their work shouldn’t need our validation, our audience applause. It can contentedly live its life without us.\n\nUntil otherwise, what we are left with is a *dead* body of collective work, detached from the grain of our crazy world and therefore complicit in our lack of engagement with its contradictions and *hypocrisies/hypo-crises*. I believe that the principles of Surrealism are thriving in contemporary alt-hip-hop, experimental pop, electronic and new jazz. So, for now, have a listen to some of my favourite contemporary Surrealists.\n\n*Surrealism Beyond Borders* is on show at Tate Modern until 29 August 2022.'
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: "https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/It's%20Nice%20to%20be%20Alive%20by%20Vegyn.jpg",
          attachmentCaption: "It's Nice to Be Alive\n\nVegyn, 2020"
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: "https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/It's%20Nice%20to%20be%20Alive%20(still)%20by%20Vegyn.jpg",
          attachmentCaption: "Still from music video for *It's Nice to be Alive* by Vegyn "
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: "https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Mazy%20Fly%20by%20Spellling.jpg",
          attachmentCaption: "Spelling, 2019"
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: "https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Under%20the%20Sun%20(still)%20by%20Spellling.jpg",
          attachmentCaption: "Still from music video for *Under the Sun* by Spelling"
      },{
          article_id: 6,
          type: 'bannerImageFill',
          attachmentLink: "https://aarchitecture.blob.core.windows.net/videos/200404_MR_TateRealisms/Arular%20by%20M.I.A..jpg",
          attachmentCaption: "M.I.A, 2005"
      },{
          article_id: 5,
          type: 'video',
          attachmentLink: "https://testingbucketwebdev.s3.ap-southeast-1.amazonaws.com/Crumbling+Land+Export.mp4"
      },{
          article_id: 5,
          type: 'titleBlockB',
      },{
          article_id: 5,
          type: 'textRight',
          text: "The Jeffersonian Grid dominates North America from the Boreal Forest to the Gulf of Mexico, and from Appalachia to the Rocky Mountains. For over two centuries, this system of rectilinear roads and property divisions has simplified a vast region of the Earth into a reliable mechanism of extraction. Under the pressures of climate change and stagnating infrastructure investment, the Grid has entered a period of slow decay. Across the United States and Canada, roads are being unpaved, and flood-prone properties bought-up and consolidated as overextended infrastructure, deindustrialization, and intensive agriculture put the landscape under increasing strain.\n\nThe project provides guidelines for the intentional abandonment of the Jeffersonian Grid, proposing that existing trends of abandonment and divestment can be strategically utilized for climate change adaptation. Intentional abandonment of roads, settlements and cultivated land could allow for the strategic distribution of resources as the maintenance of overextended infrastructure systems in the face of climate change become more acute.\n\nIn territories where sedentary settlement can no longer be taken for granted, the flow of water will become a new reference point for political organization and human settlement. From vast flood plains to a small gully within a field, landscapes can emerge whose uninhabitability can create a new space for migration and common ownership."
      },{
          article_id: 3,
          type: 'text',
          text: "*The following text is the first chapter of Artificial Aesthetics, a book co-authored by media theorist Lev Manovich and Emmanuele Arielli, associate professor of Philosophy at the IUAV in Venice. Lev and Emmanuele have syndicated their text with Antumbra.DAO. The full book is being published chapter-by-chapter at manovich.net over the course of the year./n/nThe text is a fantastic contextualisation of creative AI on the threshold of its becoming ubiquitous.*"
      },{
          article_id: 3,
          type: 'text',
          text: "**What is aesthetics?**\n\nConsider the many aesthetic choices that we make in our everyday life — picking out and matching clothes, liking photos, choosing a hairstyle, makeup, places to visit, objects to purchase, music to listen to, and so on. In all of these examples, aesthetics refers to pleasurable experiences mediated by our senses. The term can also include concepts such as style and aesthetic judgments that assess the value of an artwork, although the nature of the relationship between aesthetics and art has become an object of debate in contemporary times. We also make everyday aesthetic decisions when creating graphs, capturing and editing photos and videos, drawing images, and designing spaces and buildings. Aesthetics covers both natural and human-made objects and experiences.\n\nSince the beginning of the 21st century, computation, data analysis, machine learning, neural networks, and artificial intelligence (AI) — an all-encompassing and catchy label with a shifting definition — have all gradually entered the aesthetic realm. For example, music streaming services such as Spotify, Apple Music, and Pandora automatically recommend music we may like. Instagram’s Explore tab automatically curates photos and videos in a way that is personalized for each user. Automatic one-button photo improvement is a standard feature in all mobile and desktop apps for editing photos. Large online fashion retailers offer automatic suggestions for additional clothing items, and so on.\n\nThese systems rely on increasingly sophisticated methods to predict what people might like. Deep neural networks, for example, learn principles of aesthetic quality by directly observing people’s aesthetic choices. Earlier predictions of image quality ratings were based on classical compositional rules (such as the rule of thirds, aspect ratio, saturation, and so on) as well as on the programmers’ intuition of aesthetic value, which derived from their observation of the most liked photographs. Later, neural networks were progressively used to assign semantic labels (“meanings”) and to automatically extract aesthetically relevant features through the analysis of large databases of liked images."
      },{
          article_id: 3,
          type: 'text',
          text: "In addition to recommendations and automatic editing, AI is now widely used to generate new synthetic artifacts, including artworks, music, designs, and texts. For instance, in 2016, a deep-learning algorithm was trained to learn Rembrandt’s style by analyzing his 346 known paintings. The algorithm was subsequently given the task of generating a brand-new portrait, the result of which looked uncannily like a real Rembrandt. In the same year, researchers at the Sony Computer Science Laboratories in Paris developed a neural network, called DeepBach, that produces choral cantatas in the style of J.S. Bach. Since then, other music-generating algorithms have been created. Even YouTube videos invite viewers to participate in musical “Turing tests,” challenging them to distinguish AI-penned compositions from human ones. For people with some musical training, the task still seems straightforward, but for inexperienced listeners, this is not always the case. In 2019, Deutsche Telekom put together a team of international experts in music and AI to complete Beethoven’s unfinished 10th symphony, thus celebrating the 250th anniversary of his birth. The completed symphony, “Beethoven X — The AI Project,” premiered on October 9, 2021 in Bonn. It can be challenging to keep pace with such quick progress as incremental technological changes yield continually improved results: in 2019, an AI used the computing power of a new smartphone model to finish Schubert’s “Unfinished Symphony” (n. 8, 1822), although this was accomplished with the help of a composer who cherry-picked the best generated melodies. In 2020, an undergraduate student at Princeton University used a so-called Generative Adversarial Network (GAN) to produce traditional Chinese landscape paintings that were capable of fooling humans in a visual Turing test.\n\n<b>The encounter between AI and aesthetics is crucial because aesthetics is considered a quintessentially human domain.</b> Its intractability and complexity have long appeared as insusceptible to algorithmic reduction. For some, art, aesthetics, and creativity are the pinnacle of human abilities and therefore represent a final bulwark against the seemingly unstoppable advances of AI. In other words, this complex field becomes the ultimate testing ground for AI’s possibilities and limitations."
      },{
          article_id: 3,
          type: 'text',
          text: "In addition to recommendations and automatic editing, AI is now widely used to generate new synthetic artifacts, including artworks, music, designs, and texts. For instance, in 2016, a deep-learning algorithm was trained to learn Rembrandt’s style by analyzing his 346 known paintings. The algorithm was subsequently given the task of generating a brand-new portrait, the result of which looked uncannily like a real Rembrandt. In the same year, researchers at the Sony Computer Science Laboratories in Paris developed a neural network, called DeepBach, that produces choral cantatas in the style of J.S. Bach. Since then, other music-generating algorithms have been created. Even YouTube videos invite viewers to participate in musical “Turing tests,” challenging them to distinguish AI-penned compositions from human ones. For people with some musical training, the task still seems straightforward, but for inexperienced listeners, this is not always the case. In 2019, Deutsche Telekom put together a team of international experts in music and AI to complete Beethoven’s unfinished 10th symphony, thus celebrating the 250th anniversary of his birth. The completed symphony, “Beethoven X — The AI Project,” premiered on October 9, 2021 in Bonn. It can be challenging to keep pace with such quick progress as incremental technological changes yield continually improved results: in 2019, an AI used the computing power of a new smartphone model to finish Schubert’s “Unfinished Symphony” (n. 8, 1822), although this was accomplished with the help of a composer who cherry-picked the best generated melodies. In 2020, an undergraduate student at Princeton University used a so-called Generative Adversarial Network (GAN) to produce traditional Chinese landscape paintings that were capable of fooling humans in a visual Turing test.\n\n"
      },{
          article_id: 3,
          type: 'text',
          text: '**The encounter between AI and aesthetics is crucial because aesthetics is considered a quintessentially human domain.** Its intractability and complexity have long appeared as insusceptible to algorithmic reduction. For some, art, aesthetics, and creativity are the pinnacle of human abilities and therefore represent a final bulwark against the seemingly unstoppable advances of AI. In other words, this complex field becomes the ultimate testing ground for AI’s possibilities and limitations.\n\nStill, a prevailing opinion holds that developments like those mentioned above just *mimic* existing styles and are not creative at all. In those instances, computers receive pre-existing examples and generate variants conforming to their patterns, while trying to introduce some level of variation. Sometimes they are *uncannily* similar to genuine artworks, but this can also mean that they seem a bit off to a trained eye, lacking the final touches that would make them convincingly human. These algorithms do not generate styles of music or painting that are entirely new, instead they are instances of what we might call *computational mannerism.*\n\nHowever, it could be just a matter of time until even the experts are deceived and an AI produces artworks that are judged as aesthetically superior to their human variants. One should bear in mind that the examples mentioned above involve artwork sets with a good amount of repetition and low variability: qualities that enable neural networks to extract general features and generate new examples easily. In other words, it seems particularly straightforward to produce traditional or classical artworks as they tend to display a clear, recognizable style and follow the specific patterns of an artist, school, or tradition. Machine learning systems are ideally suited to analyse numerous occurrences of an object type with slight variations and extract the relevant features and patterns.'
      },{
          article_id: 3,
          type: 'text',
          text: 'It would, on the contrary, be very difficult to reproduce something like Marcel Duchamp’s body of work, since the AI would have to start with the very heterogeneous dataset of the artist’s oeuvre, encompassing *Fountain, Bottle Rack, the Large Glass*, the late *Étant donnés*, and so on.\n\nTypically, conservative views on art consider technical mastery as a criterion for “real art,” and many people still don’t consider something that doesn’t require technical ability to be art. However, technical ability means procedural knowledge, and AI systems are designed to deal with precisely this kind of knowledge. Clearly recognizable styles are *well-defined* problems that can be reduced to computational tasks, while the generation of variants that don’t follow compositional rules (like Duchamp’s works) results in ill-defined tasks that have no easy procedural solution.\n\n**“My kid could have done that!”**, the popular cliché directed at contemporary art, seems now, in an ironic reversal, to turn against the great and stylistically complex - but computationally scalable - art of cultural tradition: **even an AI could do that.** It is the Duchamp that remains outside of AI’s creative abilities, at least for now.'
      },{
          article_id: 3,
          type: 'text',
          text: 'Technology is the development of *tools* extending our reach and power. We have biologically limited physical strength: thanks to levers, gears, and eventually engines, we managed to overcome these limits. We have biologically limited visual acuity, but microscopes and telescopes allowed us to amplify the realm of the visible. Similarly, our cognitive skills such as calculation and memory have upper limits, but calculators and computers augmented those skills. Following this line of argumentation, one could suggest that aesthetic capacity has human limits as well, that there could be a point at which peak creativity, or peak aesthetic sensibility, is reached. Limits would be determined by both the individual, who has their own supply of sensitivity, creativity, and skills, and by the culture as a whole, which delimits what is possible within a specific artistic medium.\n\nArtificial aesthetics can be described as an augmentation of our aesthetic skills, deepening both our creative processes and our understanding and sensibility of cultural artefacts. Advanced systems would then be a further evolution of devices that are already used in creative disciplines, such as graphic programs, computer-aided design technology, music software, and so on (see later chapters on creativity, media theory, and digital culture). If in a traditional sense media are extensions of human senses, then AI is a further extension of human capabilities in mediating between us and the world.'
      },{
          article_id: 3,
          type: 'text',
          text: 'Our engagement with technology expands and modifies how we create and ultimately shapes our cultural evolution. The question arises as to whether all this has the potential to push the boundaries of our knowledge about human cultural and artistic heritage. In a futuristic scenario, machines could acquire a precise understanding of human aesthetic preferences, eventually registering how we perceive and react in front of an aesthetic object with greater accuracy than is available to humans. Machines could learn to produce aesthetic artefacts and generate new creative styles and genres. By analyzing human aesthetics and the diversity of aesthetics in human culture, they may even be able to create new “cultures” – that is, to create genuinely new types of art and aesthetics. \n\nIn discussions around AI, we often hear how machines “solve” domains that we thought were uniquely human or achieve better performances than their human competitors. On each occasion, the bar of what should be considered truly human and intelligent behaviour is raised and moved to other domains. We see – not without some concern – how the area of what we consider unreproducible by machines seems to shrink. One may wonder whether we are now witnessing this narrowing process in the aesthetic field. This raises questions such as: could machines reach a point at which we consider them truly creative? How could machines tackle the conceptual turn in contemporary art movements? What role could they have in helping us to understand “good taste” and “bad taste”? Do systems using data analysis tap in to the “unconscious” structure of our culture, or do we witness the emergence of an entirely new form of cultural production?'
      },{
          article_id: 3,
          type: 'text',
          text: 'Our engagement with technology expands and modifies how we create and ultimately shapes our cultural evolution. The question arises as to whether all this has the potential to push the boundaries of our knowledge about human cultural and artistic heritage. In a futuristic scenario, machines could acquire a precise understanding of human aesthetic preferences, eventually registering how we perceive and react in front of an aesthetic object with greater accuracy than is available to humans. Machines could learn to produce aesthetic artefacts and generate new creative styles and genres. By analyzing human aesthetics and the diversity of aesthetics in human culture, they may even be able to create new “cultures” – that is, to create genuinely new types of art and aesthetics. \n\nIn discussions around AI, we often hear how machines “solve” domains that we thought were uniquely human or achieve better performances than their human competitors. On each occasion, the bar of what should be considered truly human and intelligent behaviour is raised and moved to other domains. We see – not without some concern – how the area of what we consider unreproducible by machines seems to shrink. One may wonder whether we are now witnessing this narrowing process in the aesthetic field. This raises questions such as: could machines reach a point at which we consider them truly creative? How could machines tackle the conceptual turn in contemporary art movements? What role could they have in helping us to understand “good taste” and “bad taste”? Do systems using data analysis tap in to the “unconscious” structure of our culture, or do we witness the emergence of an entirely new form of cultural production?'
      },{
          article_id: 3,
          type: 'text',
          text: 'The original definition of aesthetics as a philosophical discipline was coined in 1750 by German philosopher Alexander Baumgarten and referred to the ancient Greek *aesthesis*, which means sensation or perception. Kant later redefined the term in his *Critics of Judgment* (1790) as the domain of subjective judgments of taste. This meant that aesthetics treated perception as a more complex notion than just sensory experience (investigated today by the psychology of perception), as it also sought to address our affective and cognitive responses to perception. Machines learn to recognize increasingly complex patterns in data that humans are not able to detect. All this raises the following question: to what extent are machine perception and pattern recognition mechanisms relevant for “aesthetic perception,” and what are the typically human aspects of aesthetic sensibility that still need to be tackled by artificial systems?\n\n**Patterns of explanation, or what do we do when we talk about aesthetics**\n\nComputational analysis may enable us to extract patterns and formal structures, but it does not provide an understanding of how such patterns affect human perception, emotion, and cognition. Patterns considered in isolation from human meaning are ultimately empty. Art historian Michael Baxandall (in his 1985 book *Patterns of Intention*) has persuasively described the essence of the critical language that we use when talking about any artwork or cultural product. For Baxandall, any discourse that we create is neither a merely factual description of features, nor a subjective report of a persons reactions, but consists in highlighting the *relationship* between the object and human responses (the meaning they give and the aesthetic reaction they manifest. This relationship is further mediated by an understanding of the object’s symbolic and cultural meanings. A critic, so to speak, tells the reader what kind of reaction is expected (or would have been expected for people in the past) in front of a specific object. Expressed in the terms of the map from the previous section, this would mean drawing a connection between the description of the object and the description of the corresponding subjective reactions.'
      },{
          article_id: 3,
          type: 'text',
          text: 'Following Baxandall, cultural and critical explanations in art are not mere descriptions or classifications: they are “primarily a representation of our thoughts about it” (*Patterns of intention*, p. 10). What we describe is a “partially interpretative description”: “one does not describe pictures, but our thoughts of having seen pictures” or at least hypotheses on those thoughts. The efficacy of a critic’s argumentation lies in his or her ability to compellingly persuade the reader that the artefact elicits the kind of reactions and thoughts that the critic is claiming to make explicit. Moreover, the critic’s use of words and concepts, while sharpening the perception of an object, at the same time deepens the meaning of the concept itself: “concepts and object reciprocally sharpen each other” (*Patterns of intention*, p 34). For example, if we describe *The Scream* by Edvard Munch (1893) as inspiring a sense of dread, then the very concept of *dread* as an aesthetic notion will be made richer by using Munch’s famous painting as a case in point.\n\nHowever, if the generated content is expected to have aesthetic value, the generative networks must take into account not only the formal dimension (*how* artefacts are made), but also their corresponding subjective interpretation and reaction, including people’s aesthetic preferences. Otherwise, we would be able to generate infinite variations of patterns, but not have a clue on how they relate to our appreciation. If description of patterns without meaning is empty, as we said, generation of patterns without human interpretation is blind.'
      },{
          article_id: 3,
          type: 'text',
          text: "In AI-media generation today, humans operate generative networks by selecting, adjusting, and tweaking the process to obtain a desired result. This result also depends on humans following their own aesthetic sensibility: for example, a music expert had to evaluate and filter the different generations of Schubert's *Unfinished Symphony*. Only algorithmic analysis of subjective responses (“Studying subjects”) would allow a progressive automation of this evaluative step.\n\nMoreover, “Studying subjects” would involve both individual and collective reactions. The latter involves analyzing historically sedimented responses towards cultural objects. Ideally, an AI capable of creating meaningful art and design would take into account the history of what exists, not only to extrapolate patterns from the artefacts, but also to interpret their collective reception, that is, how people over time have reacted to these artefacts. Thus, **using an AI to generate new cultural artefacts (and assist human creators) will require using an AI for cultural analysis.** This would necessitate bringing artificial aesthetics into contact with the various fields that deal with this issue: philosophical aesthetics, art history, psychology of art, anthropology and sociology of culture, and so on. Granted, new technical developments can generate entirely new kinds of artefacts that need not resemble the cultural production of the past. However, if we want to better grasp how these artefacts could affect people, an understanding of how we typically react and give meaning to aesthetic objects could save us from wandering in the dark. The near future may hold entirely new aesthetic artefacts, but it is unlikely to hold an entirely new human nature."
      },{
          article_id: 4,
          type: 'text',
          text: "**‘Is Photography as We Know It Dying?’**\n\nMore images are being produced, shared and seen today than ever in history. We are both constantly photographing and being photographed, with professional-level devices shrunk to a pocket size and seemingly infinite ‘cloud’ storage available at our constant disposal. The posing of the question, ‘Does photography have a future?’, may therefore seem premature or plainly absurd, given the extreme popularity of the photographic medium. However, this question is intended as a provocation, aimed at challenging our common-sense perception of the current state of things, including the frequently posited equivalence between popularity and longevity. Its theoretical impetus comes from the work of Vilém Flusser – not just his well-known texts on photography but also his important book Does Writing Have a Future?. (Flusser answers his own question in the negative, an argument that offers not so much a prophecy about our imminent illiteracy but rather a complex analysis of the inherent co-constitution of humans by and with our multiple media, with all its consequences.) Given that photography is increasingly decoupled from human agency and human vision – as evidenced in practices such as satellite imaging, drone media, CCTV and face recognition, and that the distinction between mechanical image capture and image creation is increasingly blurred (in, e.g., photogrammetry, computational photog- raphy or CGI), the question explored in this chapter concerns both the future of light-induced, mechanically produced images conventionally understood as photographs and the future of us humans as producers of and as beings produced by such images."
      },{
          article_id: 4,
          type: 'text',
          text: "Photography’s trends include miniaturisation; the increased role of software in image making, including at the image-generation stage; closer integration between photographic gear, clothing and the photographer’s body; and the proliferation of ‘nonhuman photography’, i.e., images made neither by nor for the human. Artist Trevor Paglen, who uses images from satellites, surveillance cameras and machine vision databases, goes so far as to argue that ‘Something dramatic has happened to the world of images: they have become detached from human eyes. Our machines have learnt to see without us’. In response to the question posed in one of his online contributions written for Photomuseum Winterthur, ‘Is Photography Over?’, Paglen even claims that ‘“photography,'' as it has been traditionally understood in theory and practice, has undergone a transition – it has become something else, something that’s difficult to make sense of within the existing analytic framework’.\n\n**Media Existentialism: Vilém Flusser Redux**"
      },{
          article_id: 4,
          type: 'text',
          text: "What is photography transitioning towards, then? And what kind of analytic framework might we adopt that would help us understand this transition? To work towards answering these questions about photography’s future it is worth recognising, as indicated at the beginning of this chapter, that the very posing of the question about photography’s future articulates a number of concerns regarding not just the status of a specific industry or media practice but rather some larger, or even planetary-level, concerns about our human positioning in the world and our relationship with technology, at a time when our very existence is being increasingly challenged by attempts to envisage what comes next. This may seem like too big a leap, but I want to make a proposition that, by asking, with Paglen and others, whether photography (as we know it) is over, whether it has any future, we are actually using this specific cultural-technical practice to ponder whether everything else we know – including us humans as a species with particular cultural exigencies and technical affordances – will soon be over too. We are therefore using photography, although not always in a fully conscious way, as a conduit for asking a bigger question about our own situation in the world. It is in this sense that photography functions as an example of what Amanda Lagerkvist has described as ‘existential media’, i.e., media that are capable of accounting for ‘the thrownness of the digital human condition’. This perspective analyses media life as an existential terrain which is irreducible ‘to the social, the cultural, the economic, or the political’, even if it remains intertwined with all those domains. With this existential mode of enquiry, we are also faced with another question: ‘What comes after the human?’. Building on the legacy of ghost and spirit photography, a practice combining imagination and charlatanerie to make up for personal losses before the Great War, and collective loss in its aftermath, digital and post-digital image making can be mobilised to help us imagine, visualise and frame the future – and to image and imagine our- selves as part of that future."
      },{
          article_id: 4,
          type: 'text',
          text: "The context for the exploration of these anxieties has been provided by a secular return of all sorts of existential finalisms, unfolding across different scales, some of them taking place on a species level (‘end of man’, the Sixth Extinction, coronavirus), others on a planetary one (Anthropocene, heat death). Photography and other forms of mechanical images such as films and TV have certainly played a role in aiding us with envisaging our demise. Yet, its repre- sentational role aside, it is worth delving deeper into photographic practice, with its apparatuses and networks, to trace the constitutive role of mechanical image making in enacting a certain vision of the future – or even enacting a certain future, full stop. One thinker who can help us with developing such an existential analytic framework for understanding the world today – which for him is equivalent with the world of images – is the Czech-born writer and philosopher Vilém Flusser (1920–1991). A nomad at heart if not always by choice, with the ruinous legacy of the Holocaust and antisemitism casting a dark shadow over both his family history and his work, Flusser wrote in multiple languages, disciplines, registers and styles, across several continents, decades and intellectual currents. His work on photography and other media emerged largely in the early 1980s. This was a time when media production had already been mechanised in the Benjaminian sense, with photographs’ and films’ reproducibility in the early twentieth century leading to the loss of cultural artefacts’ uniqueness as singular objects endowed with a special aura and value, and also to their democratisation and their becoming-media – but it had not yet entered the era of mass digitisation. Yet Flusser’s analyses are uncannily prescient in grasping the consequences of the automation of image production and reception, one that we see today not just in photography, video and other forms of communication such as journalism and literature, but also in politics."
      },{
          article_id: 4,
          type: 'text',
          text: "In outlining a form of what we might term ‘nomadic media existentialism’, Flusser pays particular attention to images, and even more to technical images, which he defines as ‘mosaics assembled from particles’. He differentiates them from ‘traditional images’ such as cave or oil paintings, which for him have a different relation to reality; the former are mimetic, the latter function as visualisations, i.e., models. ‘Traditional images’ are two-dimensional surfaces, while technical images are ‘without dimension’. Mark Poster is right to raise a suspicion about the rigidity or even accuracy of this distinction, one that is premised on the excessive ontologisation of the earlier forms of visual expression as ritualistic and magic-driven, at the expense of appreciating their own specific technicity. It would therefore have been more productive perhaps to extend the concept of ‘technical images’ to, say, cave paintings – which for Flusser serve as quintessential images from pre-technological magic time – in order to trace their communicative value and their formative role in producing human memory and human consciousness. Yet this reservation does not diminish the significance of Flusser’s argument, which is premised on noticing the technicity of (at least some) images in the first place, i.e., noticing their informational value."
      },{
          article_id: 4,
          type: 'text',
          text: "Photographs, addressed most explicitly in Flusser’s book Towards a Philosophy of Photography, are one class of such technical images, alongside film, television, video and other hybrid forms. Taking analogue photographs and other mechanically reproduced images as his starting point, we must note that Flusser is not really looking at them – but rather far beyond them, into the future of both images and humanity. This future is looking rather bleak; Flusser goes so far as to describe it as an ultimate catastrophe, because ‘images themselves are apocalyptic’. We will come back to this provocative idea later on. For now, let us ask whether, by not really looking at photographs, Flusser is not repeating the error of many other theorists who have thought about media without actually using them in any meaningful way, thus reducing the operational technicity of those media and the outcomes of those operations to the banality of a mere example – or, worse, to a figment of their imagination. He would be in good company here; as Flusser’s translator Nancy Roth observes, ‘Virtually all of the voices that have substantially shaped contemporary photographic “orthodoxy”, not only the historians, but critics, including Benjamin ... Barthes ... Sontag ... wrote as receivers and judges of photographs, from the position Barthes designated the Spectator’. Yet Roth jumps at Flusser’s defence by making an important differentiation: ‘As Barthes is looking at photographs, Flusser is looking at photographing ... By framing his topic as a gesture, a particular kind of movement between states of consciousness and states of affairs, Flusser was able, in a way no other writer on photography has been, to take the photographer’s part’. There is therefore a rationale for Flusser’s avoidance of looking not just at photographs but also at the photographed objects. Instead of looking at them, Flusser is looking through the photographic flow of images, and towards a future that, to cite Poster, entails ‘a more complex possibility for multiple assemblages of the human and the machine, not as prostheses for the human but as mixtures of human-machine in which the outcome of specific forms of the relation are not prefigured in the initial conceptualization of the relation’. Flusser himself argues that interest in technical images on the part of ‘future men and women’ will have an ‘existential’ value, as it will allow them to dream up new visions of the world, and of their place in it. Images for him thus serve as devices, offering an insight into the modern world in which we are all being constituted by the technical apparatus, becoming its functionaries."
      },{
          article_id: 4,
          type: 'text',
          text: "**The Image Apocalypse**\n\nTo highlight this mode of looking through the image flow is not to say that Flusser wouldn’t be able to recognise or acknowledge the content of a particular image: the specific arrangement of particles into what to a human viewer looks like a conventionally happy wedding party, a birthday celebration or a holiday in the sun. It’s just that these images are so predictable, so banal and hence so redundant in the informational sense that Flusser moves beyond their superficial value and looks at them as objects in a broader communicative sense. We could perhaps go so far as to say that Flusser perceives images the way computers (and specifically, machine vision systems) do: breaking an image into a cluster of pixels to be analysed for similarity and difference with other clusters in the database, and then matching it against the available categories and labels. Yet Flusser’s theory allows us to concede that this machinic way of looking is not just a feature of machines, or an eccentric philosopher looking, literally, against the grain. Using his theory, we can perhaps surmise that most humans now look at most images automatically, scanning them for similarity and difference, engaging in quick categorisation (on a binary level: like/not like; or a semantic one, via comments and hashtags), and going along with the media flow."
      },{
          article_id: 4,
          type: 'text',
          text: "**The Image Apocalypse**\n\nTo highlight this mode of looking through the image flow is not to say that Flusser wouldn’t be able to recognise or acknowledge the content of a particular image: the specific arrangement of particles into what to a human viewer looks like a conventionally happy wedding party, a birthday celebration or a holiday in the sun. It’s just that these images are so predictable, so banal and hence so redundant in the informational sense that Flusser moves beyond their superficial value and looks at them as objects in a broader communicative sense. We could perhaps go so far as to say that Flusser perceives images the way computers (and specifically, machine vision systems) do: breaking an image into a cluster of pixels to be analysed for similarity and difference with other clusters in the database, and then matching it against the available categories and labels. Yet Flusser’s theory allows us to concede that this machinic way of looking is not just a feature of machines, or an eccentric philosopher looking, literally, against the grain. Using his theory, we can perhaps surmise that most humans now look at most images automatically, scanning them for similarity and difference, engaging in quick categorisation (on a binary level: like/not like; or a semantic one, via comments and hashtags), and going along with the media flow."
      },{
          article_id: 4,
          type: 'text',
          text: "The framing process for Flusser’s theory of images and, more broadly, his theory of media is provided by a nexus of disciplines, from philosophy through to cybernetics and communication theory, all the way to thermodynamics and particle physics. But he also reveals a strong commitment to writing as a form of zig- zagging through ideas, concepts and modes of expression to produce what could be described as thinking in action. This is undertaken in spite of Flusser’s broader prophecy about the waning of writing as a mode of expression for the contemporary human, offering instead that we are moving towards a post-writing form of culture, driven by what he calls technical images. Indeed, for Flusser writing as the dominant mode of developing and transmitting a linear argument has no future; it has already been replaced, to a large extent, by communication via technical images. Given that Flusser was writing in the early 1980s, before digital technology radically altered our speed and form of communication, before blogging gave way to image sharing via Instagram and Snapchat and before reading was largely replaced by scrolling and touching, his theory of the end of print is indeed nothing short of prophetic. In their by now also ‘classic’ 2008 essay ‘A Life More Photographic: Mapping the Networked Image’, which analyses the state of photography in the age of the phone camera, digital snapshot and broadband, Daniel Rubinstein and Katrina Sluis look at a research project analysing the practice of users of the photo sharing platform Flickr, many of whom said they had given up blogging because it was ‘too much work’ and now favoured photography as a way of sharing their experiences. Rubinstein and Sluis argue that ‘The practices of moblogging (blogging with a mobile phone) and photoblogging (blogging with photographs rather then text) further exploit the way in which mobile phone images have become a kind of visual speech – an immediate, intimate form of communication that replaces writing’. Contemporary users of digital platforms and media thus seem to be confirming Flusser’s tongue-in-cheek assessment that ‘Images ... are not so repulsive as massive rows of fat books’."
      },{
          article_id: 4,
          type: 'text',
          text: "It is worth probing further why Flusser would resort to the aforementioned idea of the image apocalypse when looking through the images into the future. One may be tempted to equate his conceptualisation with the dismissal of the increasing photographic output in terms of an image deluge. This latter metaphor was poignantly encapsulated by Erik Kessels – a Dutch photographer, curator, advertiser and designer who can be described as the Jeff Koons of the photography world – in his installation 24 HRS in Photos. In November 2011 Kessels filled an Amsterdam art gallery with prints of images that had been uploaded to Flickr over a 24-hour period. The visitors were presented with heaps of what looked like debris, spilling everywhere. The fact that this spillage had been carefully controlled by a number of wooden frames into which it had been placed to create this illusion of a flow not only tells us something about the artist’s visual cant but also points to our wider desire for beautiful ruins, with aestheticisation of the apocalypse often having an anaesthetic function. And thus the project could easily be read as an indictment of photography today, with its pointless content, visual sameness and vapid content. Yet, following Elisabeth Kessler, it is also possible to read the installation as revealing the Flusserian apparatus in action, demonstrating human and machinic forces at work in the production of (the picture of) the world, while bringing forth a shared ‘thingness’ of our media ecologies. ‘A person chose when and how to take each picture, but broader influences – human and nonhuman – shape the way we represent, see, and live in the world’. The image apocalypse does not therefore have to mean humans perishing in the debris of the world, but rather the expiration of the Anthropocene hubris enacted by the drowning of its core subject. Well versed in the canonical texts of Western culture, including its religious writings, Flusser was no doubt aware that the apocalypse was not just a catastrophe and that its occurrence, come what may, also carried a redemptive potential."
      },{
          article_id: 4,
          type: 'text',
          text: "Before we move on to its redemptive aspects, we need to recognise that there are different levels of ‘no future’ announced in Flusser’s work, with entropy, or heat death – an occurrence resulting from the dissipation of information as explained by the second law of thermodynamics – constituting our world’s ‘event horizon’. Finalist realisations have organised the worldview of many modern philosophers – from the singular human’s horizon of death as encountered in the writing of Martin Heidegger and Jean-Paul Sartre through to the death of the sun as the star that nourishes our planet in the writings of Jean-François Lyotard. In a similar vein, Flusser’s planetary perspective is meant to allow us to come to terms with the absurdity of the world, with its ultimate lack of meaning. But this is a form of pragmatic absurdism, one devoid of wallowing in tragedy and loss. Flusser accepts from the word go that the fate of the universe is subject to chance, that the end-game of this chance is entropy and that any occurrences, be they ‘galactic spirals, living cells, or human brains’, are the result of improbable coincidences, ‘erroneous’ exceptions ‘to the general rule of increasing entropy’. Yet he quickly moves beyond that realisation to introduce a differentiation between the cosmic programme of the universe, which we can’t do very much about, and the human-designed programme of the apparatus, which remains subject to human control – or which at least entails the possibility of the human wresting away some degree of control, be it through insurgence or chance. ‘Envisioners are people who try to turn an automatic apparatus against its own condition of being automatic’. Any act of resistance can therefore only come from within and via the apparatus. Flusser may be no photographer but he himself takes on the role of an enframer and an informer – someone who can rearrange particles, or pixels, to create a new ‘mosaic’, provide new information and offer a new vision. Creativity as an act of working against the machine, not in a Luddite manner that rejects it tout court but rather in defiance of its programme, is a task he implores us all to adopt, while there is still time."
      },{
          article_id: 4,
          type: 'text',
          text: "Flusser is thus interested in photography as a mode of thinking and seeing to come, or one that has already partly come. His assessment that ‘We live in an illusory world of technical images, and we increasingly experience, recognize, evaluate, and act as a function of these images’ applies even more aptly to the era of social media and wide image sharing. Photography thus serves for Flusser as a model for understanding the functioning of the apparatus – and for taking the apparatus to task. It also becomes a laboratory for seeing otherwise, for reprogramming our vision of the world by creating better, i.e., more informed, pictures of it, with technical images being ‘phantoms that can give the world, and us, meaning’. It is in this sense that photography for Flusser has an existential significance. While he recognises that entropic decay is already part of our everyday experience, expressing itself ‘in the receivers’ zeal for the sensational – there have always to be new images because all images have long since begun to get boring’, he also observes, perhaps jokingly to some extent, that no apocalyptic catastrophe of nuclear or similar finalist kind is needed as ‘technical images are themselves the end’. Images themselves are thus ‘apocalyptic’ because they replace the linearity of writing, and thus of history, with the cybernetic feedback loop of the image flow – which becomes a magic circle of eternal return.\n\nIn the poignant assessment of the Instagram culture writer Dayna Tortorici has provided the following visceral account of what that loop actually looks like in the age of social media."
      },{
          article_id: 4,
          type: 'quote',
          text: "*What would I see? A fitness personality lunging across the sand. An adopted cat squirming in a paper bag. A Frank Lloyd Wright building. A sourdough loaf. A friend coming out as nonbinary. A mirror selfie. A handstand tutorial. Gallery opening. Nightclub candid. Outfit of the day. Medal from the Brooklyn half-marathon. New floating shelves. A screenshot of an article titled: ‘A 140- year-old tortoise wearing her 5-day-old son as a hat’. Protest. Crashing waves. Gabrielle Union’s baby. Wedding kiss. Friend’s young mother at the peak of her beauty for Mother’s Day. Ina Garten in a witch’s hat. Detail of a Bruegel painting. Brown egg in a white void, posted to @world_record_egg [verified blue checkmark], with the caption, ‘Let’s set a world record together and get the most liked post on Instagram, beating the current world record held by Kylie Jenner (18 million)! We got this [hands up emoji]’. By the time I saw it, the egg had 53,764,664 likes. The comments read: ‘What does the egg mean?’. ‘That’s a trick question’. World records are meaningless in a culture defined by historical amnesia and the relentless invention of categories, I thought, and double tapped to like the egg.”*"
      },{
          article_id: 4,
          type: 'text',
          text: "Tortorici describes the experience of the human viewer of images (in this case, herself) being faced with an Instagram flow in terms of entering into a loop of exchanges not only with other human photographers but also with the platform’s algorithms. The loops of her brain activity generated by the intensifying visual stimuli coming from the pictures of friends, strangers, objects and places eventually lead to affective overdrive. This state of high agitation is being sustained by the repetitive behaviour of sliding and tapping, with the viewer’s eyes and fingers enacting their own loopy dance in search of yet another dopamine hit. Flusser points out that the ‘general consensus between images and people’ – as evidenced in the popularity scores achieved by various images – inscribes itself in the repetitive cycle: nature – culture – waste – nature. We may update it as ‘Flower – like – skip – the great outdoors. Woman I vaguely know – heart – unheart – God I hate her. Food – avo on toast – skip – #sohungry’. But there is an escape from, or at least opening within, that world of ‘meaninglessness’ and ‘historical amnesia’ on its way to heat death.The redemptive aspect of Flusser’s apocalypse lies in the redefinition of the human as part of the ‘composting’ loop. This entails dissolving the myth of the human ‘I’ as ‘a core that must be preserved and developed’."
      },{
          article_id: 4,
          type: 'text',
          text: "Repositioned as ‘an abstract hook on which to hang concrete circumstances, the “I” reveals itself to be nothing’. The Flusserian apocalypse thus involves destroying the Judeo-Christian image of the human as a being, made, albeit imperfectly, in the image of God and equipped with some core qualities, qualities whose nature has to be both veiled and revered. For Flusser, the “I” only emerges in a dialogue. Building on the philosophy of Martin Buber while also giving it a cybernetic twist in his image of a society as a ‘dialogical cerebral web’, Flusser claims that the ‘“I” is the one to whom someone says “you” ’. The communication model of subjectivity is not just linked to acts of speech; as previously stated, for Flusser the medium really becomes the message – and the messenger. Our consciousness is thus seen as being shaped by the media we make and use, and which also make and use us. This model of (say, Instagram- driven) subjectivity dispenses with universal humanist signal points such as choice, decision and free will. Flusser does nevertheless offer an opening within this cybernetic-naturalistic theorisation of the human. A being produced, literally, from media res, one whose brain ‘appeared as an accident in the natural game of chance’, the human has the possibility of mobilising this aleatory game as a strategy. S/he can do this because the brain has an inbuilt tendency to turn against chance, defy accident and reject entropy. However, for the human’s negentropic tendency to be actualised certain conditions need to be created. Flusser’s whole oeuvre, one might argue, is premised on identifying those conditions."
      },{
          article_id: 4,
          type: 'text',
          text: "**Photography and Future-Making**\n\nAs well as being authors of their own destruction, human beings – who have inaugurated and then labelled a geological epoch in their name – are also a guarantee of our planet’s survival. Humans thus can be said to have an inbuilt counterapocalyptic tendency. Even if this survival is just a delay, humans are an opportunity for the world, as well as functioning as its existential threat. The answer about the future – of images, writing, the world, or anything else – is therefore also a matter of temporal scale. Images themselves, and, in particular, technical images as produced and exchanged via platforms such as Instagram, Facebook or Snapchat, can serve as delaying tactics in this process of information dissipation, even if the majority of them do nothing of the kind. As an Instagram user Flusser would have no doubt been bemused by the banality, sameness and predictability of the output. Yet his existential-level conclusion, ‘I play with images ... to coexist’, would surely serve as an encouragement not to sign off too quickly – from social media, from sociality and from the world as we know it.\n\nThe answer to the question ‘Does photography have a future?’ thus depends on who is posing it and what time scale they operate on. If it’s a curator or a gallery owner interested in securing investment on their Henri Cartier-Bresson or Ansel Adams, they probably have a few good years left. If it’s a photojournalist or a professional wedding photographer, the writing is on the wall, at least as far as high income is concerned – unless they can undergo a cross-media shift to become a personal TV channel. For those who are too busy posting on Instagram or editing their selfies to be even interested in posing it, because most of the things they know come from living in the constant image flow, some other questions maybe more pertinent than the one about the state of the photographic medium, its supporting institutions and its industry: When looking at, sharing and con- tributing to the media flow, what kind of future do you see, for yourself and the world? What kind of existence can you carve out and enframe from the media and image flow?"
      },{
          article_id: 4,
          type: 'text',
          text: "In the Judeo-Christian culture, the world was seen as ‘an image made in God’s likeness’. It was a representational model of the world, whereby humans were seen as part of God’s creation. In the universe of the image apparatus, the world is an image without a divine origin. What is more, it has become increasingly impossible to distinguish between a representation and a model. We could go so far as to argue that now all images have become what filmmaker Harun Farocki has termed ‘operational images’, carrying the potential of an execution of a function. According to Flusser, ‘From now on, we are the ones who project meaning on the world. And technical images are such projections’. Reprogramming the apparatus thus also means taking responsibility for our role in the co-creation of images, be it with technical devices or our cortico-corporeal apparatus, in full knowledge that we are neither sole authors nor sole recipients of the incessant media and image flow – although we may be the only ones for whom shaping this flow into a set of meanings becomes an ethico-political task, rather than just a pre-programmed function to be executed. The fact that the majority of people function as if that was not the case, running the programmes of the apparatus in and with their lives, cameras, phones and other media, only makes this task more urgent."
      },{
          article_id: 4,
          type: 'text',
          text: "Flusser himself already pronounced in 1985, several decades before the wide adoption of photogrammetry, CGI and AI-driven image making, that ‘photography is about to become redundant’. With this, he was referring to the increased generation of synthetic images, as a result of which it had become impossible to ‘distinguish between depictions and models’. Yet, even if the medium and the practice of photography as we know them may indeed become obsolete, the function of photography will no doubt survive for a long time yet – although its execution, in the fully informational guise, will perhaps only be executed by the very few. Like writing, which is ‘a mesh of accident and necessity’ yet which is nevertheless ‘experienced’ by us code-driven and code-making humans ‘as a free gesture’, photography will present us with new opportunities, beyond trying to seek meaning and order in the world, be it via religion or everyday semiosis. To approach the medium of photography through the ‘existential register’ outlined by Lagerkvist is to shift photography’s future role from memory-making to future-making, while repositioning the photographer as the very maker (or, to use Flusser’s term, ‘envisioner’) of those futures. The future photographer’s gesture of pointing at the world can be expected to generate a whole new ‘revolutionary attitude’ , one which will involve projecting meaning onto the world. Technical images, be it in their photographic or post-photographic guises, are capable of functioning as such projections. Through this photography has the potential to ‘give absurdity a meaning’ – not in a semiotic sense, but rather through reframing the photographic act and gesture as meaningful in themselves – and thus serve as a life force, a generator of experiences transmitted as images. Transcending its representative function as the ‘pencil of nature’ or ‘the mirror of life’, photography can instead become the future, for better or for worse."
      }]);
  })
};