exports.seed = function (knex) {
    return knex("article").del()
    .then(async()=>{
        return knex("article").insert([{
            type: "text",
            author: "Tiziana Terranova and Ravi Sundaram",
            title: "Colonial Infrastructures and Techno-social Networks",
            subtitle: "The techno-social is the form of the social that comes after its end. It is neither a virtual nor a global digital community, but a component of the milieu generated by a new technical being—the digital computational network.",
            moduleType:"text",
            heroImage:"https://images.e-flux-systems.com/highway.jpg,1920",
            datePublished: "27th February 2021"
        },{
            type: "video",
            author: "Amnesia Scanner",
            title: "AS Crust",
            subtitle: "Amnesia Scanner returned today with AS CRUST. In the visual for the song, a kid keeps kicking an emaciated-looking four-legged animal.",
            moduleType:"video",
            heroImage:"https://i.ytimg.com/vi/xjytGvXdgqA/maxresdefault.jpg",
            datePublished: "10th January 2021"
        },{
            type: "photography",
            author: "Bas Princen",
            title: "Gold Standard",
            subtitle: "From a new book looking at the visual and personal backstory to one particular photograph, 'the Ringroad (Houston)', from 2005.",
            moduleType:"photography",
            heroImage:"https://i0.wp.com/bldgblog.com/wp-content/uploads/2017/02/RingRoadHouston.jpg?w=840&ssl=1",
            datePublished: "13th March 2022"
        },{
            type: "text",
            author: "Yeha Kim",
            title: "Data Warfare and the Warm War",
            subtitle: "In the UK alone, there are over 1500 sites, which monitor air quality - these monitoring networks, in turn, continuously gather and process data in real-time. Although these networks continuously produce a wide range of both descriptive and exceedance statistics, not all data produced is easily accessible for the public realm, and neither does it remain unchallenged by other information sources.",
            moduleType:"text",
            heroImage:"https://aarchitecture.blob.core.windows.net/videos/ezgif.com-gif-maker.gif",
            datePublished: "22nd March 2022"
        }, {
            type: "photography",
            author: "Simon Denny",
            title: "Dotcomseance",
            subtitle: "In the UK alone, there are over 1500 sites, which monitor air quality - these monitoring networks, in turn, continuously gather and process data in real-time. Although these networks continuously produce a wide range of both descriptive and exceedance statistics, not all data produced is easily accessible for the public realm, and neither does it remain unchallenged by other information sources.",
            moduleType:"main",
            heroImage:"https://pbs.twimg.com/media/FG0JjTxXwA0kM90.jpg:large",
            datePublished: "21th April 2022"
        }]);
    })
    .then(()=>{
        return knex('attachment').del();
    })
    .then(()=>{
        return knex('attachment').insert([{
            article_id: 1,
            attachmentLink: 'https://google.com',
            attachmentType: 'text'
        },{
            article_id: 2,
            attachmentLink: 'https://google.com',
            attachmentType: 'photograph',
        },{
            article_id: 3,
            attachmentLink: 'https://google.com',
            attachmentType: 'video',
        }]);
    })
    .then(()=>{
        return knex('tag').del();
    })
    .then(()=>{
        return knex('tag').insert([{
            tag: 'infrastructure',
        },{
            tag: 'urbanisation',
        },{
            tag: 'automation',
        },{
            tag: 'robotics',
        },{
            tag: 'earth systems',
        }])
    })
    .then(()=>{
        return knex('article_tag').del();
    })
    .then(()=>{
        return knex('article_tag').insert([{
            article_id: 1,
            tag_id: 1
        }, {
            article_id: 1,
            tag_id: 2
        }, {
            article_id: 2,
            tag_id: 3
        }, {
            article_id: 2,
            tag_id: 4
        }])
    })
};